service: ui-render

plugins:
    - serverless-webpack
    - serverless-offline

package:
    individually: true
    include:
        - ../../node_modules/**

custom:
    serviceName: ui
    stage: ${opt:stage, '${self:custom.serviceName}'}
    serverless-offline:
        noPrependStageInUrl: true
        httpPort: 3000
        lambdaPort: 3001
    deploymentBucketName: ${self:custom.stage}-${opt:region, self:provider.region}-serverless-deployment-bucket
    webpack:
        includeModules:
            nodeModulesRelativeDir: '../../'
            packagePath: '../../package.json'
        webpackConfig: './webpack.config.js'
        packager: 'yarn'
    environment:
        ELASTICACHE_URL:
            dev: 'redis://:testpass@localhost:6379'
            prod: ${ssm:/prod/redis.url, ''}
        MONGO_DB_URL:
            dev: 'mongodb://root:root@localhost:27017/evento?authSource=admin'
            prod: ${ssm:/prod/mongo.url, ''}

provider:
    name: aws
    runtime: nodejs14.x
    logRetentionInDays: 30
    region: ap-southeast-2
    tags:
        service: ${self:custom.serviceName}
    environment:
        STAGE: ${opt:stage}
        ELASTICACHE_URL: ${self:custom.environment.ELASTICACHE_URL.${self:custom.stage}}
        MONGO_DB_URL: ${self:custom.environment.MONGO_DB_URL.${self:custom.stage}}

functions:
    - ${file(./sls/definitions.yaml)}
